### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by wangranche** [ahonn/Nada#1]
报错：
`Traceback (most recent call last):
                                    File "/usr/local/bin/nada", line 9, in <module>
       load_entry_point('nada==0.1.3', 'console_scripts', 'nada')()
                                                                     File "/usr/local/lib/python2.7/site-packages/nada-0.1.3-py2.7.egg/nada/__init__.py", line 12, in start
               Menu().start()
                               File "/usr/local/lib/python2.7/site-packages/nada-0.1.3-py2.7.egg/nada/menu.py", line 54, in __init__
                                                        self.database.load()
                                                                              File "/usr/local/lib/python2.7/site-packages/nada-0.1.3-py2.7.egg/nada/database.py", line 27, in load
                       self.save()
                                    File "/usr/local/lib/python2.7/site-packages/nada-0.1.3-py2.7.egg/nada/database.py", line 30, in save
                                                             os.remove(self.path)
 OSError: [Errno 2] No such file or directory: '/Users/Jackie/.nada/database.json'
  %`

**Comment by ahonn** [comment]
试试 `sudo pip install nada==0.1.3.1`
